version: "3"

services:
  db:
    image: postgres:12.3
    hostname: db
    env_file:
      - .env
    networks:
      - backend

  redis:
    image: library/redis:5.0-alpine
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: ${DOCKER_REPOSITORY}/app:${DOCKER_APP_VERSION}
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db
      - redis

networks:
  backend:
    driver: bridge
